Update build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -51,16 +51,16 @@ jobs:
           echo "KERNEL_VERSION=$KVER.$KPATCH" >> $GITHUB_ENV
 
       - name: Patch live defconfig for GKI
-        working-directory: kernel/oneplus/sm8550
-        run: |
-          if [ ! -f ../../lineage_oneplus11_defconfig ]; then
-            echo "lineage_oneplus11_defconfig missing!"
-            exit 1
-          fi
-          cp ../../lineage_oneplus11_defconfig arch/arm64/configs/
-          echo "# CONFIG_OPLUS_SENSOR_DEVINFO is not set" >> arch/arm64/configs/lineage_oneplus11_defconfig
-          echo "# CONFIG_OPLUS_FEATURE_SENSOR_CFG is not set" >> arch/arm64/configs/lineage_oneplus11_defconfig
-          echo "Patched lineage_oneplus11_defconfig to disable Oplus sensors"
+  working-directory: kernel/oneplus/sm8550
+  run: |
+    if [ ! -f ../../lineage_oneplus11_defconfig ]; then
+      echo "lineage_oneplus11_defconfig missing!"
+      exit 1
+    fi
+    cp ../../lineage_oneplus11_defconfig arch/arm64/configs/
+    echo "# CONFIG_OPLUS_SENSOR_DEVINFO is not set" >> arch/arm64/configs/lineage_oneplus11_defconfig
+    echo "# CONFIG_OPLUS_FEATURE_SENSOR_CFG is not set" >> arch/arm64/configs/lineage_oneplus11_defconfig
+    echo "Patched lineage_oneplus11_defconfig to disable Oplus sensors"
 
       - name: Setup KernelSU-Next
         working-directory: kernel/oneplus/sm8550
